### PR TITLE
Draw borders with Direct2D

### PR DESCRIPTION
**Pull request by keifufu**
- fuckery, barely usable, laggy, fuck.

### CODE REVIEW

**Comment by modkavartini** [comment]
agreed

**Comment by LGUG2Z** [comment]
https://github.com/LGUG2Z/komorebi/blob/a511cbd26366699de788c941df773413667c0334/komorebi/src/border_manager/border.rs

komorebi's border code is now in an isolated module instead of all over the place if you want to take some inspiration for thicc borders

**Comment by keifufu** [comment]
I mean if komorebi does it, people can just use that instead :D

**Comment by DreamMaoMao** [comment]
https://github.com/lukeyou05/tacky-borders

This idea has already been implemented in this project,it is more stable than komorebi's border

**Comment by keifufu** [comment]
In case it wasn't clear: I do not intend to work on this PR. This entire project was practically abandoned right after I published it, if it wasn't for the fact that requested features (other than this) take no more than a few minutes to implement.

**Pull request closed without merging**
